--DELANTEROS
INSERT INTO jugadores (Nombre, Media, Imagen, Pos) VALUES
('Sergio Agüero', 89, 'img/delanteros/Aguero.jpg', 'delantero'),
('Marco Asensio', 83, 'img/delanteros/Asensios.jpg', 'delantero'), 
('André Ayew', 76, 'img/delanteros/Ayew.jpg', 'delantero'), 
('Karim Benzema', 87, 'img/delanteros/Benzema.jpg', 'delantero'), 
('Bernardo Silva', 87, 'img/delanteros/BernardoSilva.jpg', 'delantero') ,
('Brahim Díaz', 73, 'img/delanteros/Brahim.jpg', 'delantero'), 
('Felipe Caicedo', 78, 'img/delanteros/Caicedo.jpg', 'delantero'), 
('Cristiano Ronaldo', 93, 'img/delanteros/Cristiano.jpg', 'delantero'), 
('Johan Cruyff', 94, 'img/delanteros/Cruyff.jpg', 'delantero') ,
('Kasper Dolberg', 76, 'img/delanteros/Dolberg.jpg', 'delantero') ,
('Radamel Falcao', 83, 'img/delanteros/Falcao.jpg', 'delantero') ,
('Eden Hazard', 91, 'img/delanteros/Hazard.jpg', 'delantero') ,
('Ciro Immobile', 86, 'img/delanteros/Immobile.jpg', 'delantero') ,
('Jese Rodriguez', 75, 'img/delanteros/Jese.jpg', 'delantero') ,
('Joselu', 74, 'img/delanteros/Joselu.jpg', 'delantero') ,
('Stevan Jovetic', 78, 'img/delanteros/Jovetic.jpg', 'delantero') ,
('Lautaro Martínez', 81, 'img/delanteros/Lautaro.jpg', 'delantero') ,
('Loren Moron', 80, 'img/delanteros/Kean.jpg', 'delantero') ,
('Lionel Messi', 94, 'img/delanteros/Messi.jpg', 'delantero') ,
('Moise Kean', 76, 'img/delanteros/Kean.jpg', 'delantero'), 
('Neymar JR', 92, 'img/delanteros/Neymar.jpg', 'delantero') ,
('Martin Odegaard', 78, 'img/delanteros/Odergaard.jpg', 'delantero') ,
('Marcus Rashford', 83, 'img/delanteros/Rashford.jpg', 'delantero') ,
('Raúl González Blanco', 92, 'img/delanteros/Raul.jpg', 'delantero') ,
('Ronaldinho', 94, 'img/delanteros/Ronaldinho.jpg', 'delantero') ,
('Ronaldo Nazario', 96, 'img/delanteros/Ronaldo.jpg', 'delantero') ,
('Leroy Sané', 86, 'img/delanteros/Sane.jpg', 'delantero') ,
('Luis Suarez', 89, 'img/delanteros/Suarez.jpg', 'delantero') ,
('Sam Vokes', 73, 'img/delanteros/Vokes.jpg', 'delantero')

--CENTROCAMPISTAS
INSERT INTO jugadores (Nombre, Media, Imagen, Pos) VALUES
('Sergio Busquets', 89, 'img/centrocampistas/Busquets.jpg', 'centrocampista'),
('Dani Ceballos', 81, 'img/centrocampistas/Ceballos.jpg', 'centrocampista'),
('Kevin De Bruyne', 91, 'img/centrocampistas/DeBruyne.jpg', 'centrocampista'),
('Frenkie De Jong', 85, 'img/centrocampistas/DeJong.jpg', 'centrocampista'),
('Julian Draxler', 83, 'img/centrocampistas/Draxler.jpg', 'centrocampista'),
('Mohamed Elneny', 77, 'img/centrocampistas/Elneny.jpg', 'centrocampista'),
('Ricardo Kaká', 91, 'img/centrocampistas/Kaka.jpg', 'centrocampista'),
("N'Golo Kanté", 89, 'img/centrocampistas/Kante.jpg', 'centrocampista'),
('Toni Kroos', 89, 'img/centrocampistas/Kroos.jpg', 'centrocampista'),
('Frank Lampard', 90, 'img/centrocampistas/Lampard.jpg', 'centrocampista'),
('Micheal Laudrup', 91, 'img/centrocampistas/Laudrup.jpg', 'centrocampista'),
('Diego Maradona', 97, 'img/centrocampistas/Maradona.jpg', 'centrocampista'),
('Juan Mata', 82, 'img/centrocampistas/Mata.jpg', 'centrocampista'),
('Scott McTominay', 77, 'img/centrocampistas/Mctominay.jpg', 'centrocampista'),
('Luka Modric', 90, 'img/centrocampistas/Modric.jpg', 'centrocampista'),
('Jesus Navas', 82, 'img/centrocampistas/Navas.jpg', 'centrocampista'),
('Nolito', 78, 'img/centrocampistas/Nolito.jpg', 'centrocampista'),
('Tomás Pina', 77, 'img/centrocampistas/Pina.jpg', 'centrocampista'),
('Andrea Pirlo', 92, 'img/centrocampistas/Pirlo.jpg', 'centrocampista'),
('Ivan Rakitic', 86, 'img/centrocampistas/Rakitic.jpg', 'centrocampista'),
('Saul', 85, 'img/centrocampistas/Saul.jpg', 'centrocampista'),
('Clarence Seedorf', 91, 'img/centrocampistas/Seedorf.jpg', 'centrocampista'),
('Patrick Vieira', 91, 'img/centrocampistas/Vieira.jpg', 'centrocampista'),
('Zinedine Zidane', 96, 'img/centrocampistas/Zidane.jpg', 'centrocampista')

--DEFENSAS
INSERT INTO jugadores (Nombre, Media, Imagen, Pos) VALUES
('Marcos Alonso', 81, 'img/defensas/Alonso.jpg', 'defensa'),
('Eric Bailly', 80, 'img/defensas/Bailly.jpg', 'defensa'),
('Franco Baresi', 93, 'img/defensas/Baresi.jpg', 'defensa'),
('Fabio Cannavaro', 92, 'img/defensas/Cannavaro.jpg', 'defensa'),
('Giorgio Chiellini', 89, 'img/defensas/Chiellini.jpg', 'defensa'),
('Matthijs de Ligt', 85, 'img/defensas/DeLigt.jpg', 'defensa'),
('Dakonam Djené', 83, 'img/defensas/Djene.jpg', 'defensa'),
('Junior Firpo', 79, 'img/defensas/Firpo.jpg', 'defensa'),
('Mario Gaspar', 79, 'img/defensas/Gaspar.jpg', 'defensa'),
('Gusito', 99, 'img/defensas/Gusito.jpg', 'defensa'),
('Vincent Kompany', 83, 'img/defensas/Kompany.jpg', 'defensa'),
('Paolo Maldini', 94, 'img/defensas/Maldini.jpg', 'defensa'),
('Marcelo', 85, 'img/defensas/Marcelo.jpg', 'defensa'),
('Ferland Mendy', 80, 'img/defensas/Mendy.jpg', 'defensa'),
('Nacho Fernández', 82, 'img/defensas/Nacho.jpg', 'defensa'),
('Gerard Pique', 88, 'img/defensas/Pique.jpg', 'defensa'),
('Carles Puyol', 92, 'img/defensas/Puyol.jpg', 'defensa'),
('Sergio Ramos', 89, 'img/defensas/Ramos.jpg', 'defensa'),
('Sergio Reguilón', 77, 'img/defensas/Reguilon.jpg', 'defensa'),
('Roberto Carlos', 91, 'img/defensas/RobertoCarlos.jpg', 'defensa'),
('Marcel Schmelzer', 76, 'img/defensas/Schmelzer.jpg', 'defensa'),
('Nelson Semedo', 82, 'img/defensas/Semedo.jpg', 'defensa'),
('Thiago Silva', 87, 'img/defensas/Silva.jpg', 'defensa'),
('Dimitrios Siovas', 76, 'img/defensas/Siovas.jpg', 'defensa'),
('Kieran Trippier', 80, 'img/defensas/Trippier.jpg', 'defensa'),
('Virgil van Dijk', 90, 'img/defensas/VanDijk.jpg', 'defensa'),
('Raphaël Varane', 85, 'img/defensas/Varane.jpg', 'defensa')

--PORTEROS
INSERT INTO jugadores (Nombre, Media, Imagen, Pos) VALUES
('Antonio Adán', 81, 'img/porteros/Adan.jpg', 'portero'),
('Igor Akinfeev', 80, 'img/porteros/Akinfeev.jpg', 'portero'),
('Alisson Becker', 89, 'img/porteros/Alisson.jpg', 'portero'),
('Alphonse Areola', 82, 'img/porteros/Areola.jpg', 'portero'),
('Diego Benaglio', 74, 'img/porteros/Benaglio.jpg', 'portero'),
('Claudio Bravo', 77, 'img/porteros/Bravo.jpg', 'portero'),
('Cifuentes', 73, 'img/porteros/Cifuentes.jpg', 'portero'),
('Dani Giménez', 74, 'img/porteros/DaniGimenez.jpg', 'portero'),
('David De Gea', 89, 'img/porteros/DeGea.jpg', 'portero'),
('Gianluigi Donnarumma', 85, 'img/porteros/Donnarumma.jpg', 'portero'),
('Fabricio', 76, 'img/porteros/Fabricio.jpg', 'portero'),
('Oliver Kahn', 94, 'img/porteros/Kahn.jpg', 'portero'),
('Jens Lehmann', 90, 'img/porteros/Lehmann.jpg', 'portero'),
('Lopes', 85, 'img/porteros/Lopes.jpg', 'portero'),
('Manuel Neuer', 88, 'img/porteros/Neuer.jpg', 'portero'),
('Jan Oblak', 91, 'img/porteros/Oblak.jpg', 'portero'),
('Peter Schmeichel', 92, 'img/porteros/Peter Schmeichel.jpg', 'portero'),
('Marc-André ter Stegen', 90, 'img/porteros/TerStegen.jpg', 'portero'),
('Edwin van der Sar', 91, 'img/porteros/VanDerSar.jpg', 'portero'),
('Lev Yashin', 94, 'img/porteros/Yashin.jpg', 'portero')